[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Disable secret scanning for specific environment variables
  SECRETS_SCAN_OMIT_KEYS = "SMTP_HOST,SMTP_PORT,SMTP_SECURE,SMTP_USER,SMTP_PASSWORD,CONTACT_FORM_RECIPIENT,CAREERS_FORM_RECIPIENT"